version: '3'

services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      # keep container-installed node_modules (don't let host overwrite it)
      - /app/node_modules
    restart: unless-stopped